export default {
    extends: 'stylelint-config-standard',
    ignoreFiles: [
        'demonstrator/**',
        '**/node_modules/**',
        '**/site.webmanifest',
        '**/dist/**',
        '**/.git/**',
        '**/tests/**',
        '!**/*.css',
        '**/*.js',
        '**/*.mjs',
        '**/*.ts',
        '**/*.svg',
        '**/*.png',
        '**/*.pdf',
        '**/*.xlsx',
        '**/*.xls',
        '**/*.json',
        '**/*.txt',
        '**/*.html',
        '**/*.lock',
        '**/*.yaml',
        '**/*.md',
    ],
    rules: {
        'selector-class-pattern': '^(?:--)?[a-z][a-z0-9-]*$',
        'property-no-vendor-prefix': null,
    },
}
